### ISSUE TITLE
mask

### ISSUE THREAD

**Issue by liwenjielongren** [votchallenge/aibu#5]
hello，how to get the mask in the VOT2016 dataset

**Comment by liwenjielongren** [comment]
![image](https://user-images.githubusercontent.com/52265815/91725469-5f6ea380-ebd1-11ea-9099-ad26148799c2.png)
I want to use the VOT2016 method to annotate my data, how should i do?

**Comment by lukacu** [comment]
Aibu does not support segmentation masks at the moment, we have not used it to generate masks for any VOT challenge. Closing the issue. If you are interested in other aspects of segmentation masks in tracking, please use our support forum, but be more precise about what you are trying to do.
